# Generated by Django 6.1.1 on 2026-09-30 05:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=500, verbose_name='Цена')),
                ('art_key', models.CharField(default='sakura', max_length=40)),
                ('accent', models.CharField(default='#ff8fb8', max_length=9)),
                ('accent2', models.CharField(default='#ffd6e7', max_length=9)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('sort', models.PositiveSmallIntegerField(default=100)),
                ('background', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['sort', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('series', models.CharField(choices=[('azure', 'Голубой сад'), ('hana', 'Цветение Хана'), ('kitsune', 'Хвост Кицуне'), ('snowfall', 'Снегопад'), ('neon', 'Неоновый Токио'), ('abyss', 'Бездна'), ('lumen', 'Свет'), ('vermilion', 'Алый веер'), ('orchid', 'Орхидея'), ('halo', 'Нимб'), ('moonlight', 'Лунный свет'), ('forge', 'Кузня снов')], max_length=20)),
                ('rarity', models.CharField(choices=[('sakura', '🌸 Легенда сакуры'), ('mythic', '💞 Мифическая'), ('epic', '💎 Эпическая'), ('rare', '💙 Редкая'), ('common', '🍃 Обычная')], default='common', max_length=12)),
                ('element', models.CharField(choices=[('sakura', 'Сакура'), ('moon', 'Луна'), ('star', 'Звёзды'), ('snow', 'Снег'), ('rain', 'Дождь'), ('fire', 'Пламя'), ('forest', 'Лес'), ('sea', 'Море'), ('dream', 'Сон'), ('dark', 'Тень')], default='sakura', max_length=12)),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Титул')),
                ('quote', models.CharField(blank=True, max_length=200, verbose_name='Цитата')),
                ('origin', models.CharField(blank=True, max_length=120, verbose_name='Происхождение')),
                ('image_seed', models.PositiveIntegerField(default=1, unique=True)),
                ('art_style', models.PositiveSmallIntegerField(default=0)),
                ('power', models.PositiveSmallIntegerField(default=50, verbose_name='Сила')),
                ('cuteness', models.PositiveSmallIntegerField(default=50, verbose_name='Милота')),
                ('elegance', models.PositiveSmallIntegerField(default=50, verbose_name='Элегантность')),
                ('spirit', models.PositiveSmallIntegerField(default=50, verbose_name='Дух')),
                ('lore', models.TextField(blank=True, verbose_name='История')),
                ('released', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Аниме-девочка',
                'verbose_name_plural': 'Аниме-девочки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('petals', models.PositiveIntegerField(default=2500, verbose_name='Лепестки')),
                ('total_opens', models.PositiveIntegerField(default=0, verbose_name='Всего открытий')),
                ('legendaries', models.PositiveIntegerField(default=0, verbose_name='Легенд выбито')),
                ('pity_counter', models.PositiveIntegerField(default=0, verbose_name='До гаранта')),
                ('last_daily', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='OpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakura.case')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakura.girl')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sakura.player')),
            ],
            options={
                'verbose_name': 'История открытий',
                'verbose_name_plural': 'История открытий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Вес %')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='sakura.case')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='sakura.girl')),
            ],
            options={
                'verbose_name': 'Дроп из кейса',
                'verbose_name_plural': 'Дропы из кейсов',
                'unique_together': {('case', 'girl')},
            },
        ),
        migrations.CreateModel(
            name='OwnedGirl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Копий')),
                ('shards', models.PositiveIntegerField(default=0, verbose_name='Осколки')),
                ('first_at', models.DateTimeField(auto_now_add=True)),
                ('last_at', models.DateTimeField(auto_now=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='sakura.girl')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_girls', to='sakura.player')),
            ],
            options={
                'verbose_name': 'В коллекции',
                'verbose_name_plural': 'В коллекции',
                'ordering': ['-count'],
                'unique_together': {('player', 'girl')},
            },
        ),
    ]
