# Generated by Django 6.1.1 on 2026-09-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['sort', 'price'], 'verbose_name': 'РљРµР№СЃ', 'verbose_name_plural': 'РљРµР№СЃС‹'},
        ),
        migrations.AlterModelOptions(
            name='casedrop',
            options={'verbose_name': 'Р”СЂРѕРї РёР· РєРµР№СЃР°', 'verbose_name_plural': 'Р”СЂРѕРїС‹ РёР· РєРµР№СЃРѕРІ'},
        ),
        migrations.AlterModelOptions(
            name='girl',
            options={'ordering': ['name'], 'verbose_name': 'РђРЅРёРјРµ-РґРµРІРѕС‡РєР°', 'verbose_name_plural': 'РђРЅРёРјРµ-РґРµРІРѕС‡РєРё'},
        ),
        migrations.AlterModelOptions(
            name='openlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Р\x98СЃС‚РѕСЂРёСЏ РѕС‚РєСЂС‹С‚РёР№', 'verbose_name_plural': 'Р\x98СЃС‚РѕСЂРёСЏ РѕС‚РєСЂС‹С‚РёР№'},
        ),
        migrations.AlterModelOptions(
            name='ownedgirl',
            options={'ordering': ['-count'], 'verbose_name': 'Р’ РєРѕР»Р»РµРєС†РёРё', 'verbose_name_plural': 'Р’ РєРѕР»Р»РµРєС†РёРё'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Р\x98РіСЂРѕРє', 'verbose_name_plural': 'Р\x98РіСЂРѕРєРё'},
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='РќР°Р·РІР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.PositiveIntegerField(default=500, verbose_name='Р¦РµРЅР°'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tagline',
            field=models.CharField(blank=True, max_length=160, verbose_name='РЎР»РѕРіР°РЅ'),
        ),
        migrations.AlterField(
            model_name='casedrop',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Р’РµСЃ %'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='cuteness',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='РњРёР»РѕС‚Р°'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='elegance',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Р\xadР»РµРіР°РЅС‚РЅРѕСЃС‚СЊ'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='element',
            field=models.CharField(choices=[('sakura', 'РЎР°РєСѓСЂР°'), ('moon', 'Р›СѓРЅР°'), ('star', 'Р—РІС‘Р·РґС‹'), ('snow', 'РЎРЅРµРі'), ('rain', 'Р”РѕР¶РґСЊ'), ('fire', 'РџР»Р°РјСЏ'), ('forest', 'Р›РµСЃ'), ('sea', 'РњРѕСЂРµ'), ('dream', 'РЎРѕРЅ'), ('dark', 'РўРµРЅСЊ')], default='sakura', max_length=12),
        ),
        migrations.AlterField(
            model_name='girl',
            name='lore',
            field=models.TextField(blank=True, verbose_name='Р\x98СЃС‚РѕСЂРёСЏ'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Р\x98РјСЏ'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='origin',
            field=models.CharField(blank=True, max_length=120, verbose_name='РџСЂРѕРёСЃС…РѕР¶РґРµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='power',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='РЎРёР»Р°'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='quote',
            field=models.CharField(blank=True, max_length=200, verbose_name='Р¦РёС‚Р°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='rarity',
            field=models.CharField(choices=[('sakura', '🌸 Р›РµРіРµРЅРґР° СЃР°РєСѓСЂС‹'), ('mythic', '💞 РњРёС„РёС‡РµСЃРєР°СЏ'), ('epic', '💎 Р\xadРїРёС‡РµСЃРєР°СЏ'), ('rare', '💙 Р\xa0РµРґРєР°СЏ'), ('common', '🍃 РћР±С‹С‡РЅР°СЏ')], default='common', max_length=12),
        ),
        migrations.AlterField(
            model_name='girl',
            name='series',
            field=models.CharField(choices=[('azure', 'Р“РѕР»СѓР±РѕР№ СЃР°Рґ'), ('hana', 'Р¦РІРµС‚РµРЅРёРµ РҐР°РЅР°'), ('kitsune', 'РҐРІРѕСЃС‚ РљРёС†СѓРЅРµ'), ('snowfall', 'РЎРЅРµРіРѕРїР°Рґ'), ('neon', 'РќРµРѕРЅРѕРІС‹Р№ РўРѕРєРёРѕ'), ('abyss', 'Р‘РµР·РґРЅР°'), ('lumen', 'РЎРІРµС‚'), ('vermilion', 'РђР»С‹Р№ РІРµРµСЂ'), ('orchid', 'РћСЂС…РёРґРµСЏ'), ('halo', 'РќРёРјР±'), ('moonlight', 'Р›СѓРЅРЅС‹Р№ СЃРІРµС‚'), ('forge', 'РљСѓР·РЅСЏ СЃРЅРѕРІ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='girl',
            name='spirit',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Р”СѓС…'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='РўРёС‚СѓР»'),
        ),
        migrations.AlterField(
            model_name='ownedgirl',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='РљРѕРїРёР№'),
        ),
        migrations.AlterField(
            model_name='ownedgirl',
            name='shards',
            field=models.PositiveIntegerField(default=0, verbose_name='РћСЃРєРѕР»РєРё'),
        ),
        migrations.AlterField(
            model_name='player',
            name='legendaries',
            field=models.PositiveIntegerField(default=0, verbose_name='Р›РµРіРµРЅРґ РІС‹Р±РёС‚Рѕ'),
        ),
        migrations.AlterField(
            model_name='player',
            name='petals',
            field=models.PositiveIntegerField(default=2500, verbose_name='Р›РµРїРµСЃС‚РєРё'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pity_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Р”Рѕ РіР°СЂР°РЅС‚Р°'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_opens',
            field=models.PositiveIntegerField(default=0, verbose_name='Р’СЃРµРіРѕ РѕС‚РєСЂС‹С‚РёР№'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=50, verbose_name='Р¦РµРЅР°')),
                ('status', models.CharField(choices=[('active', 'РђРєС‚РёРІРЅРѕ'), ('sold', 'РџСЂРѕРґР°РЅРѕ'), ('cancelled', 'РћС‚РјРµРЅРµРЅРѕ')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought', to='sakura.player')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='sakura.girl')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='sakura.player')),
            ],
            options={
                'verbose_name': 'Р›РѕС‚ РЅР° Р±РёСЂР¶Рµ',
                'verbose_name_plural': 'Р›РѕС‚С‹ РЅР° Р±РёСЂР¶Рµ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='sakura.player')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakura.girl')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='sakura.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='sakura.player')),
            ],
            options={
                'verbose_name': 'РЎРґРµР»РєР°',
                'verbose_name_plural': 'РЎРґРµР»РєРё',
                'ordering': ['-created_at'],
            },
        ),
    ]
