"""Build a static copy of the site for GitHub Pages.

Pages cannot run Django, so this renders every page through the real views with
`static_mode` on, pre-renders the procedural SVG art, and dumps the catalogue as
data.json. `static/js/static-mode.js` then takes over gacha, collection, profile
and the market using localStorage.
"""

import json
import re
import shutil
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.test import Client
from django.utils import timezone

from sakura import art
from sakura.models import Case, Girl, Listing, Player, RARITY_META, RARITY_ORDER, Rarity


class Command(BaseCommand):
    help = "Render a static GitHub Pages build of the site"

    def add_arguments(self, parser):
        parser.add_argument("out", nargs="?", default="site")
        parser.add_argument("--clean", action="store_true", help="delete the output dir first")
        parser.add_argument(
            "--base",
            default="",
            help="subpath the site is served from, e.g. /sakura (for deploying into a subdirectory)",
        )

    def handle(self, *args, **options):
        out = Path(options["out"]).resolve()
        if options["clean"] and out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True, exist_ok=True)

        base = "/" + options["base"].strip("/") if options["base"].strip("/") else ""
        settings.SAKURA_STATIC_EXPORT = True

        self._assets(out)
        self._art(out)
        self._data_json(out)
        self._pages(out)
        (out / ".nojekyll").write_text("", encoding="utf-8")
        (out / "robots.txt").write_text("User-agent: *\nAllow: /\n", encoding="utf-8")
        if base:
            self._rebase(out, base)
            self._robots(out, base)

        self.stdout.write(self.style.SUCCESS(f"\nГотово: {out}  (base: {base or '/'})"))

    # ------------------------------------------------------------------ rebase
    def _rebase(self, out: Path, base: str):
        """Rewrite root-absolute links so the build works from a subdirectory.

        Django emits `/cases/`, `/static/...` and the JS fetches `/data.json`. Everything
        is generated by us, so a single pass over HTML and JS is enough.
        """
        rx = re.compile(r'(["\'])/(?!/|data:)')
        targets = list(out.rglob("*.html")) + list((out / "static" / "js").glob("*.js"))
        targets.append(out / "data.json")
        n = 0
        for p in targets:
            src = p.read_text(encoding="utf-8")
            new = rx.sub(lambda m: f"{m.group(1)}{base}/", src)
            if new != src:
                p.write_text(new, encoding="utf-8")
                n += 1
        self.stdout.write(f"  rebased    {n} files -> {base}/")

    def _robots(self, out: Path, base: str):
        (out / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {base}/\n", encoding="utf-8")

    # ---------------------------------------------------------------- assets
    def _assets(self, out: Path):
        # {% static %} emits /static/... so everything must live under out/static
        src = Path(settings.BASE_DIR) / "static"
        dst = out / "static"
        for sub in ("css", "js"):
            shutil.copytree(src / sub, dst / sub, dirs_exist_ok=True)
        self.stdout.write("  assets     static/css, static/js")

    # ------------------------------------------------------------------- art
    def _art(self, out: Path):
        av = out / "static" / "art" / "avatar"
        av.mkdir(parents=True, exist_ok=True)
        for g in Girl.objects.all():
            (av / f"{g.image_seed}.svg").write_text(
                art.avatar_svg(g.image_seed, size=320, accent=g.accent), encoding="utf-8"
            )
        cs = out / "static" / "art" / "case"
        cs.mkdir(parents=True, exist_ok=True)
        for c in Case.objects.all():
            (cs / f"{c.slug}.svg").write_text(
                art.case_svg(c.art_key, c.accent, c.accent2, seed=21), encoding="utf-8"
            )
        logo = out / "static" / "art" / "logo.svg"
        logo.write_text(art.logo_svg(), encoding="utf-8")
        self.stdout.write(f"  art        {Girl.objects.count()} аватаров, {Case.objects.count()} баннеров")

    # ------------------------------------------------------------------ data
    def _data_json(self, out: Path):
        girls = [
            {
                "id": g.pk,
                "name": g.name,
                "slug": g.slug,
                "title": g.title,
                "rarity": g.rarity,
                "rarityLabel": g.get_rarity_display(),
                "color": RARITY_META[g.rarity]["color"],
                "glow": RARITY_META[g.rarity]["glow"],
                "tier": RARITY_META[g.rarity]["tier"],
                "element": g.element,
                "elementLabel": g.get_element_display(),
                "accent": g.accent,
                "series": g.series,
                "lore": g.lore,
                "quote": g.quote,
                "power": g.power,
                "cuteness": g.cuteness,
                "elegance": g.elegance,
                "spirit": g.spirit,
                "image": g.image_url,
                "fallback": f"/static/art/avatar/{g.image_seed}.svg",
                "url": f"/girl/{g.slug}/",
                "baseValue": g.base_value,
                "inCases": [c.slug for c in Case.objects.filter(drops__girl=g).distinct()],
            }
            for g in Girl.objects.order_by("pk")
        ]

        cases = [
            {
                "id": c.pk,
                "name": c.name,
                "slug": c.slug,
                "tagline": c.tagline,
                "description": c.description,
                "price": c.price,
                "badge": c.badge,
                "isNew": c.is_new,
                "accent": c.accent,
                "accent2": c.accent2,
                "art": f"/static/art/case/{c.slug}.svg",
                "url": f"/case/{c.slug}/",
                "hasLegendary": c.drops.filter(girl__rarity=Rarity.SAKURA).exists(),
                "pool": c.drops.count(),
                "odds": [
                    {"pct": o["pct"], "color": o["color"], "label": o["label"]} for o in c.odds_rows()
                ],
                "drops": [
                    {"girl": d.girl_id, "w": round(float(d.weight), 4)}
                    for d in c.drops.select_related("girl")
                ],
            }
            for c in Case.objects.all()
        ]

        labels = dict(Rarity.choices)
        payload = {
            "version": 1,
            "builtAt": timezone.now().isoformat(),
            "rarityOrder": [r.value for r in RARITY_ORDER],
            "rarities": [
                {
                    "key": r.value,
                    "label": labels[r.value],
                    "color": RARITY_META[r.value]["color"],
                    "total": Girl.objects.filter(rarity=r.value).count(),
                }
                for r in RARITY_ORDER
            ],
            "pityLimit": Player.PITY_LIMIT,
            "dailyAmount": Player.DAILY_AMOUNT,
            "startPetals": 3000,
            "minPrice": Listing.MIN_PRICE,
            "feePercent": int(Listing.SELL_FEE * 100),
            "maxLots": 4,
            "girls": girls,
            "cases": cases,
        }
        (out / "data.json").write_text(
            json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8"
        )
        self.stdout.write(f"  data.json  {len(girls)} девочек, {len(cases)} кейсов")

    # ----------------------------------------------------------------- pages
    def _pages(self, out: Path):
        allowed = list(settings.ALLOWED_HOSTS)
        if "testserver" not in allowed:
            settings.ALLOWED_HOSTS = [*allowed, "testserver"]
        try:
            c = Client()
            c.get("/")  # establish a guest session so get_player() is happy
            routes = [("/", "index.html"), ("/cases/", "cases/index.html")]
            routes += [(f"/case/{x.slug}/", f"case/{x.slug}/index.html") for x in Case.objects.all()]
            routes += [(f"/girl/{x.slug}/", f"girl/{x.slug}/index.html") for x in Girl.objects.all()]
            routes += [
                ("/collection/", "collection/index.html"),
                ("/market/", "market/index.html"),
                ("/hall/", "hall/index.html"),
                ("/profile/", "profile/index.html"),
            ]

            for path, rel in routes:
                resp = c.get(path)
                if resp.status_code != 200:
                    raise SystemExit(f"!! {path} -> {resp.status_code}")
                dest = out / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(resp.content)

            (out / "404.html").write_bytes(c.get("/hall/").content)
        finally:
            settings.ALLOWED_HOSTS = allowed
        self.stdout.write(f"  pages      {len(routes) + 1} html")
